---
tags: [任务调度]
projects: [Spring 框架]
---
:toc:
:spring_version: current
:icons: font
:source-highlighter: prettify
:project_id: gs-scheduling-tasks
这个指引将带你一步一步了解如何使用Spring进行任务调度。

== 你将做出什么

您将构建一个应用程序，它使用Spring的 `@Scheduled` 注释每五秒打印当前的时间。

== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]
== 创建计划任务
既然已经建立了项目，那么就可以创建计划任务了。

`src/main/java/hello/ScheduledTasks.java`
[source,java]
----
include::complete/src/main/java/hello/ScheduledTasks.java[]
----

`Scheduled` 注解定义特定方法何时运行。
NOTE: 这个例子使用 `fixedRate` ，用于指定的每次方法开始调用之间的时间间隔。还有一些注解 http://docs.spring.io/spring/docs/{spring_version}/spring-framework-reference/html/scheduling.html#scheduling-annotation-support-scheduled[other options], 比如 `fixedDelay`, 用于指定每次任务完成的时间间隔。 还有 http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html[使用 `@Scheduled(cron=". . .")` 表达式用于更复杂任务调度的表达式].

== 启用调度

虽然计划任务可以嵌入到Web应用程序和WAR文件中，但下面演示的更简单的方法创建了一个独立的应用程序。你打包所有东西在一个单一，可执行jar文件，由一个good old java ` main() `方法驱动。

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc[]

http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#scheduling-enable-annotation-support[`@EnableScheduling`] 注解将确保后台任务执行者被创建。没有他将不会有任务调度。


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]



日志输出显示，您可以从日志中看到它在后台线程上。你应该每5秒看到你预定的任务打印：

....
[...]
2016-08-25 13:10:00.143  INFO 31565 --- [pool-1-thread-1] hello.ScheduledTasks : The time is now 13:10:00
2016-08-25 13:10:05.143  INFO 31565 --- [pool-1-thread-1] hello.ScheduledTasks : The time is now 13:10:05
2016-08-25 13:10:10.143  INFO 31565 --- [pool-1-thread-1] hello.ScheduledTasks : The time is now 13:10:10
2016-08-25 13:10:15.143  INFO 31565 --- [pool-1-thread-1] hello.ScheduledTasks : The time is now 13:10:15
....

== 总结

祝贺你!您创建了具有预定任务的应用程序。事实上，实际的代码比构建文件短！这种技术可以应用在在任何类型的工程中的应用。

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

